import React, { useState } from 'react';
import { Bot, Sparkles, Zap, ArrowRight, Loader2, AlertCircle } from 'lucide-react';
import { QuizPack, Difficulty } from '../types';

interface AiQuizGeneratorProps {
  onStartQuiz: (quizPack: QuizPack) => void;
  primaryColor: string;
}

const QUICK_TOPICS = [
  '80s Synthwave & Rock',
  'Quantum Computing',
  'Marvel Cinematic Universe',
  'Ancient Mythology',
  'Artificial Intelligence & Robotics',
  'World Food & Gastronomy',
  'Space Exploration & NASA',
  'Video Game History',
];

export const AiQuizGenerator: React.FC<AiQuizGeneratorProps> = ({ onStartQuiz, primaryColor }) => {
  const [topicInput, setTopicInput] = useState('');
  const [difficulty, setDifficulty] = useState<Difficulty>('Medium');
  const [questionCount, setQuestionCount] = useState<number>(5);
  const [isGenerating, setIsGenerating] = useState(false);
  const [errorMsg, setErrorMsg] = useState<string | null>(null);

  const handleGenerateQuiz = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!topicInput.trim()) return;

    setIsGenerating(true);
    setErrorMsg(null);

    try {
      const response = await fetch('/api/generate-quiz', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          topic: topicInput.trim(),
          difficulty,
          questionCount,
        }),
      });

      const data = await response.json();

      if (!response.ok || !data.success) {
        throw new Error(data.error || 'Failed to generate AI quiz.');
      }

      const generatedQuiz: QuizPack = {
        id: `ai-${Date.now()}`,
        title: data.quiz.title || `AI Quiz: ${topicInput}`,
        category: data.quiz.category || 'AI Custom',
        description: data.quiz.description || `Custom trivia generated by Gemini AI on ${topicInput}`,
        iconName: 'Sparkles',
        difficulty,
        estimatedMinutes: Math.round(questionCount * 0.6),
        questions: data.quiz.questions.map((q: any, idx: number) => ({
          id: `ai-q-${idx}`,
          question: q.question,
          options: q.options,
          correctIndex: q.correctIndex,
          explanation: q.explanation,
          category: data.quiz.category || 'AI Custom',
          difficulty,
        })),
        isAiGenerated: true,
      };

      onStartQuiz(generatedQuiz);
    } catch (err: any) {
      console.error(err);
      setErrorMsg(err.message || 'Error generating quiz. Please try again.');
    } finally {
      setIsGenerating(false);
    }
  };

  return (
    <div className="max-w-3xl mx-auto px-4 py-8 animate-fadeIn" id="ai-quiz-generator-container">
      {/* Banner */}
      <div className="text-center mb-8">
        <div
          className="inline-flex items-center gap-2 px-4 py-1.5 rounded-full font-bold text-xs uppercase tracking-wider mb-4 border font-mono"
          style={{
            backgroundColor: `rgba(var(--color-primary-rgb), 0.12)`,
            borderColor: `rgba(var(--color-primary-rgb), 0.25)`,
            color: primaryColor,
          }}
        >
          <Bot className="w-4 h-4" /> Powered by Gemini AI
        </div>
        <h1 className="text-2xl sm:text-3xl font-extrabold app-text mb-2">
          AI Custom Quiz Generator
        </h1>
        <p className="text-xs sm:text-sm app-text-muted max-w-lg mx-auto">
          Type ANY custom topic under the sun, and Gemini AI will instantly craft a 30s challenge quiz for you!
        </p>
      </div>

      {/* Main Generator Card */}
      <div className="app-surface rounded-2xl p-6 sm:p-8 app-border border shadow-lg mb-8">
        <form onSubmit={handleGenerateQuiz} className="space-y-6">
          {/* Topic Input */}
          <div>
            <label className="text-xs font-bold uppercase tracking-wider app-text-subtle block mb-2 font-mono">
              Topic or Niche Prompt
            </label>
            <div className="relative">
              <input
                type="text"
                required
                maxLength={80}
                value={topicInput}
                onChange={e => setTopicInput(e.target.value)}
                placeholder="e.g. 90s Hip Hop, Quantum Physics, Greek Gods, Electric Cars..."
                className="w-full pl-4 pr-10 py-3.5 rounded-xl app-surface-subtle app-border border text-sm font-semibold app-text focus:outline-none focus:ring-2 focus:ring-indigo-500 transition-all"
              />
              <Sparkles className="w-5 h-5 absolute right-4 top-1/2 -translate-y-1/2 pointer-events-none" style={{ color: primaryColor }} />
            </div>
          </div>

          {/* Quick Suggestion Chips */}
          <div>
            <span className="text-[11px] font-bold uppercase tracking-wider app-text-subtle block mb-2 font-mono">
              Trending Quick Topics
            </span>
            <div className="flex flex-wrap gap-2">
              {QUICK_TOPICS.map((topic, idx) => (
                <button
                  type="button"
                  key={idx}
                  onClick={() => setTopicInput(topic)}
                  className="px-3 py-1.5 rounded-xl app-surface-subtle hover:opacity-80 app-text font-semibold text-xs transition-colors app-border border"
                >
                  + {topic}
                </button>
              ))}
            </div>
          </div>

          {/* Options Grid */}
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-4 pt-2 app-border border-t">
            {/* Difficulty Selector */}
            <div>
              <label className="text-xs font-bold uppercase tracking-wider app-text-subtle block mb-2 font-mono">
                Difficulty Level
              </label>
              <div className="grid grid-cols-3 gap-2">
                {(['Easy', 'Medium', 'Hard'] as Difficulty[]).map(d => (
                  <button
                    type="button"
                    key={d}
                    onClick={() => setDifficulty(d)}
                    className={`py-2.5 rounded-xl font-bold text-xs transition-all ${
                      difficulty === d
                        ? 'text-white shadow-md'
                        : 'app-surface-subtle app-text app-border border hover:opacity-80'
                    }`}
                    style={difficulty === d ? { backgroundColor: primaryColor } : {}}
                  >
                    {d}
                  </button>
                ))}
              </div>
            </div>

            {/* Question Count Selector */}
            <div>
              <label className="text-xs font-bold uppercase tracking-wider app-text-subtle block mb-2 font-mono">
                Number of Questions
              </label>
              <div className="grid grid-cols-2 gap-2">
                {[5, 10].map(cnt => (
                  <button
                    type="button"
                    key={cnt}
                    onClick={() => setQuestionCount(cnt)}
                    className={`py-2.5 rounded-xl font-bold text-xs transition-all ${
                      questionCount === cnt
                        ? 'text-white shadow-md'
                        : 'app-surface-subtle app-text app-border border hover:opacity-80'
                    }`}
                    style={questionCount === cnt ? { backgroundColor: primaryColor } : {}}
                  >
                    {cnt} Questions
                  </button>
                ))}
              </div>
            </div>
          </div>

          {/* Error Message */}
          {errorMsg && (
            <div className="p-4 rounded-xl bg-rose-500/10 border border-rose-500/20 text-rose-500 text-xs font-bold flex items-center gap-2">
              <AlertCircle className="w-4 h-4 shrink-0" />
              <span>{errorMsg}</span>
            </div>
          )}

          {/* Submit Action */}
          <button
            type="submit"
            disabled={isGenerating || !topicInput.trim()}
            className="w-full py-4 rounded-xl font-bold text-sm text-white shadow-lg flex items-center justify-center gap-2 transition-all hover:opacity-95 active:scale-95 disabled:opacity-50 disabled:cursor-not-allowed"
            style={{ backgroundColor: primaryColor }}
          >
            {isGenerating ? (
              <>
                <Loader2 className="w-5 h-5 animate-spin" />
                Crafting AI Trivia Questions...
              </>
            ) : (
              <>
                <Zap className="w-5 h-5" />
                Generate AI Quiz Now
                <ArrowRight className="w-4 h-4" />
              </>
            )}
          </button>
        </form>
      </div>
    </div>
  );
};
